server:
   port: 9002
   tomcat:
     uri-encoding: utf-8
spring:
  profiles:
    active: online
  application:
     name:  ugc-dev
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
      enabled: true
  messages:
    encoding: UTF-8
  jpa:
    show-sql: true
  data:
     mongodb:
       uri: mongodb://dev:dev.asdweffea@47.102.199.98:10001/ugc_dev
  redis:
     host: 139.199.88.87
     port: 6379
     password:
     pool:
       max-active: 8
       max-wait: 300000
       max-idle: 8
       min-idle: 0
     timeout: 50000
  mail:
     host: smtp.163.com
     username: justdjtop@163.com
     password: 963852zx
     default-encoding: UTF-8
     properties:
       mail:
         smtp:
           auth: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://122.152.193.63:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${eureka.instance.appname}:${server.port}
    appname:  ugc-dev
#    ip-address: 139.199.88.87
swagger2:
  enable: true
  baseDir: /static
#阿里云服务配置
aliyun:
  sms:
    accesskey:
      id: 123
      secret: 123
    signname: 123
    template:
      code:
        login: 123
        password: 123
  oss:
    endPiont: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI7vmBPuYcYiOj
    accessKeySecret: ZAvxOCDAnpH5ibhXqv3MjYlg369DPE
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
base-path: /
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
